trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.0.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    cd back
    dotnet restore
  displayName: 'Restore dependencies'

- script: |
    cd back
    dotnet build --configuration $(buildConfiguration)
  displayName: 'Build project'

- script: |
    cd back
    dotnet test --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run unit tests'
